In [ ]:
import numpy as np
import csv
fileid ="1vtQ442CfzInJrVkD3SwTOYUku8MEAmn6" #Here I have extracted this file from Google drive
!wget -O Heart_Disease_Prediction.csv "https://drive.google.com/uc?id=1vtQ442CfzInJrVkD3SwTOYUku8MEAmn6"
x_t=[]
y_t=[]
fi= open("Heart_Disease_Prediction.csv", "r")
reader= csv.reader(fi)
head= next(reader)
for r in reader:
  a=[]
  for k in r[:-1]:
    a.append(float(k))
  x_t.append(a)
  if r[-1]== "Presence":
    y_t.append(1)
  else:
    y_t.append(0)
x_train= np.array(x_t)
y_train=np.array(y_t)
#x_train= (x_train - np.mean(x_train, axis=0))/(np.max(x_train, axis=0)- np.min(x_train, axis=0)+ 1e-8)

--2026-02-09 14:06:33--  https://drive.google.com/uc?id=1vtQ442CfzInJrVkD3SwTOYUku8MEAmn6
Resolving drive.google.com (drive.google.com)... 173.194.69.139, 173.194.69.102, 173.194.69.138, ...
Connecting to drive.google.com (drive.google.com)|173.194.69.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1vtQ442CfzInJrVkD3SwTOYUku8MEAmn6 [following]
--2026-02-09 14:06:33--  https://drive.usercontent.google.com/download?id=1vtQ442CfzInJrVkD3SwTOYUku8MEAmn6
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 108.177.127.132, 2a00:1450:4013:c07::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|108.177.127.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11928 (12K) [application/octet-stream]
Saving to: ‘Heart_Disease_Prediction.csv’

Heart_Disease_Predi 100%[===================>]  11.65K  --.-KB/s    in 0s      

2026-02-09 14:06:3

In [ ]:
m= x_train.shape[1]
n= y_train.shape[0]
def sigmoid(z):
  s= 1/(1+np.exp(-z))
  return s
def relu(z):
  r= np.maximum(0,z)
  return r
def dsigmoid(z):
  s1= sigmoid(z)
  return (s1*(1-s1))

In [ ]:
def dense(a_in, W, b, g):
  units= W.shape[1]
  a_out=np.zeros(units)
  z_out= np.zeros(units)
  for j in range(units):
    w=W[:,j]
    z= np.dot(w, a_in) + b[j]
    a_out[j] = g(z)
    z_out[j]=z
  return (z_out, a_out)

In [ ]:
def sequential(x, W1, b1, W2, b2):
  z1, a1= dense(x, W1, b1, sigmoid)
  z2, a2= dense(a1, W2, b2, sigmoid)
  return (a1, a2, z1, z2)

In [ ]:
def predict(x, w1, w2, b1, b2):
  A1, A2, Z1, Z2 = sequential(x, w1, w2, b1, b2)
  if A2>=0.5:
    print("Disease present")
    return 1
  else:
    print("No disease")
    return 0

In [ ]:
import random
h=3
w1= np.random.randn(m,h)*0.001
b1= np.random.randn(h)*0.01
w2= np.random.randn(h,1)*0.01
b2= np.random.randn(1)*0.01
#w1= np.full((m, h), 0.001, dtype=float)
#b1= np.full(h, 0.001, dtype= float)
#w2= np.full((h,1), 0.001, dtype=float)
#b2= np.full(1, 0, dtype=float)
alpha=0.001
epochs=10000

for epoch in range(epochs):
  dw1= np.zeros_like(w1)
  dw2= np.zeros_like(w2)
  db1= np.zeros_like(b1)
  db2= np.zeros_like(b2)
  loss=0
  for i in range(n):

    xi= x_train[i]
    yi= y_train[i]
    #print(xi)
    a1, a2, z1, z2= sequential(xi, w1, b1, w2, b2)
    #print(w2.shape)
    loss+= -(yi*np.log(a2)+(1-yi)*np.log(1-a2))
    dz2= a2-yi
    dw2+=a1.reshape(-1,1)*dz2
    db2+=dz2
    dz1= w2.reshape(-1)*dz2*dsigmoid(z1)
    dw1+=xi.reshape(-1,1)*dz1
    db1+= dz1
  #print(w2.shape)
  w1-=alpha*dw1/n
  w2-=alpha*dw2/n
  b1-=alpha*db1/n
  b2-=alpha*db2/n
  loss/=n
  if epoch%500==0:
    print("Iteration no.:", epoch, "Loss=", loss)
print("W1 final:", w1, "W2 final:", w2, "b1 final:", b1, "b2 final:", b2)


Iteration no.: 0 Loss= [0.6924119]
Iteration no.: 500 Loss= [0.68909283]
Iteration no.: 1000 Loss= [0.68634829]
Iteration no.: 1500 Loss= [0.67957991]
Iteration no.: 2000 Loss= [0.67216383]
Iteration no.: 2500 Loss= [0.66506807]
Iteration no.: 3000 Loss= [0.658257]
Iteration no.: 3500 Loss= [0.65192775]
Iteration no.: 4000 Loss= [0.6462465]
Iteration no.: 4500 Loss= [0.64119775]
Iteration no.: 5000 Loss= [0.63669219]
Iteration no.: 5500 Loss= [0.63263503]
Iteration no.: 6000 Loss= [0.62894398]
Iteration no.: 6500 Loss= [0.62555142]
Iteration no.: 7000 Loss= [0.6224026]
Iteration no.: 7500 Loss= [0.619453]
Iteration no.: 8000 Loss= [0.61666582]
Iteration no.: 8500 Loss= [0.61400984]
Iteration no.: 9000 Loss= [0.61145779]
Iteration no.: 9500 Loss= [0.60898503]
W1 final: [[-7.48803165e-02 -7.53310598e-02 -7.35618839e-02]
 [-2.06250686e-02 -1.73599723e-02 -1.95707323e-02]
 [-3.70914546e-02 -3.62979644e-02 -3.78236907e-02]
 [-8.42298402e-02 -8.19088202e-02 -8.30864732e-02]
 [-2.05848078e-02